### ISSUE TITLE
Request: Make it not muted when WiFi disconnects

### ISSUE THREAD

**Issue by aliceyounce39** [legendsayantan/ShizuTools#34]
I'm so thankful for this app, especially for the SoundMaster. The problem is I have an unstable internet connection, and the app always gets muted because my internet disconnects.

Will it ever be updated where the app won't get muted when WiFi disconnects, so I don't have to do the whole process w/ USB debugging, Wireless debugging, and Shizuku every time? Thanks in advance.

**Comment by legendsayantan** [comment]
By WiFi disconnection, do you mean that wireless debugging gets disabled? Because in theory, Even if wireless debugging stops, shizuku should not stop if USB debugging is on, until your device runs out of ram or device restarts. I would advise you to tweak with other settings in dev options, if any of them help.

**Comment by aliceyounce39** [comment]
For some reason, "disable permission monitoring" gets disabled when WiFi gets disabled, and I need to have both USB debugging and that option enabled for Shizuku & ShizuTools to work. It's actually okay now.
